# Base image
FROM node:16-alpine

# Set the working directory
WORKDIR /app

# Copy the package.json file
COPY package.json .

# Install dependencies
RUN npm install

# Copy the application code
COPY C:\Users\lovep\OneDrive\Desktop\Websocket Server\DockerFiles\server.js .

# Start the WebSocket server
CMD ["node", "server.js"]
